/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary': '#ffffff',
        outline: '#76777c',
        background: '#fbf9f8',
        'outline-variant': '#c6c6cc',
        'inverse-primary': '#c2c6d8',
        'on-background': '#1b1c1c',
        'tertiary-container': '#1f201d',
        'primary-fixed': '#dee2f4',
        'on-error-container': '#93000a',
        'inverse-surface': '#303030',
        'surface-container': '#efeded',
        'on-primary-fixed-variant': '#424655',
        'secondary-fixed': '#ffe088',
        'surface-variant': '#e4e2e2',
        secondary: '#735c00',
        'on-secondary-container': '#745c00',
        'surface-dim': '#dbd9d9',
        'on-secondary-fixed-variant': '#574500',
        'secondary-fixed-dim': '#e9c349',
        'on-error': '#ffffff',
        'secondary-container': '#fed65b',
        tertiary: '#070806',
        'on-secondary-fixed': '#241a00',
        'error-container': '#ffdad6',
        'primary-fixed-dim': '#c2c6d8',
        'on-tertiary-fixed-variant': '#474744',
        'surface-bright': '#fbf9f8',
        'tertiary-fixed-dim': '#c8c6c2',
        'on-primary-container': '#828697',
        'surface-tint': '#595e6d',
        'tertiary-fixed': '#e4e2dd',
        'on-surface-variant': '#45464c',
        'inverse-on-surface': '#f2f0f0',
        'surface-container-highest': '#e4e2e2',
        'surface-container-lowest': '#ffffff',
        'on-secondary': '#ffffff',
        'on-tertiary-container': '#888783',
        surface: '#fbf9f8',
        'on-surface': '#1b1c1c',
        'on-primary-fixed': '#161b28',
        'primary-container': '#1a1f2c',
        'surface-container-low': '#f5f3f3',
        'on-primary': '#ffffff',
        error: '#ba1a1a',
        'on-tertiary-fixed': '#1b1c19',
        primary: '#030612',
        'surface-container-high': '#eae8e7',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '16px',
        'container-margin': '24px',
        unit: '8px',
        'section-gap': '64px',
      },
      fontFamily: {
        'body-lg': ['Work Sans', 'sans-serif'],
        'headline-lg': ['Playfair Display', 'serif'],
        'headline-lg-mobile': ['Playfair Display', 'serif'],
        'label-md': ['Work Sans', 'sans-serif'],
        caption: ['Work Sans', 'sans-serif'],
        'display-md': ['Playfair Display', 'serif'],
        'display-lg': ['Playfair Display', 'serif'],
        'body-md': ['Work Sans', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.1em', fontWeight: '500' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'display-md': ['36px', { lineHeight: '44px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
      animation: {
        'scroll-up': 'scrollUp 40s linear infinite',
        'star-pulse': 'starPulse 3s ease-in-out infinite',
      },
      keyframes: {
        scrollUp: {
          '0%': { transform: 'translateY(0)' },
          '100%': { transform: 'translateY(-50%)' },
        },
        starPulse: {
          '0%, 100%': { opacity: '0.2', transform: 'scale(1)' },
          '50%': { opacity: '0.7', transform: 'scale(1.5)' },
        },
      },
    },
  },
  plugins: [],
}
